0405 과제 제출
Altu-Bitu-2/AltuBitu2_assignment pull request #10
Opened 2022-04-10 15:06 UTC by minkyung01

#### 내용 & 질문
> 1080번과 11000번 코드 오류 점검 부탁드립니다..ㅠㅠ

#### <기존 제출>
> 1080, 11000, 13305

#### <추가 제출>
>

2022-04-11 07:05 UTC, hoit1302 requested changes
정말 항상 열심히 풀어주셔서 이것저것 더 생각해보고 저도 검색해보면서 많이 배우는 것 같아요!
바쁘신 와중에 과제하시느라 너무 수고하셨습니다!!!
정말 사소한 코멘트들도 있고 정말 궁금하셨던 것에 대한 답변도 해드린 것 같아요. 
11000번은 조금 어려울 수도 있는데 끙끙대면서 열심히 생각해보는 시간들이 절대 헛되지 않을거에요!!
다시 열심히 생각해봅시다 🙌🏻
앗 그리고 민경님께 꼭 해드리고 싶은 말이 사실 하나 있는데요,,, 출력하면서 디버깅하는 연습을 해보세요!
큼직하게 출력 코드만 짜보면 바로 코드의 문제점을 쉽게 찾을 수 있는 경우가 참 많습니다 ㅎㅎ
출력이 귀찮다면 사용하시는 툴의 디버깅 기능을 활용해보아도 좋을 것 같아요 :)
하지만 코테에서는 디버깅 기능을 막고 풀이하라고 하는 경우가 많아서 출력 디버깅도 가끔 챙겨서 연습해보면 좋을 것 같아요 ㅎㅎ
수정하시면 저 다시 리뷰어로 호출해주세요! 감사합니다 🥰

2022-04-11 07:05 UTC, hoit1302 commented on 0405/1080.cpp
> +    }
> 계속 코드가 실행이 안 되는데... 혹시 코드에서 오류 찾아주실 수 있을까요?

A. cin은 어떤 문자를 구분해서 입력받나요? 행렬 A와 B를 입력 받은 뒤에 잘 입력 되었는지 한 번 출력해봐요! 
저도 똑같은 오류를 범했어서 바로 보이네요 ㅎㅎㅎ (에디터 끄고 켜고 한번 했어여...ㅎㅎ)

2022-04-11 07:05 UTC, hoit1302 commented on 0405/1080.cpp
> +int B[50][50]; //행렬 B
p3. 
변수 이름을 대문자로 하면, 자칫 상수로 착각할 수도 있어요! 
c++ 컨벤션에 따라서 변수 이름은 소문자로 작성하시는 걸 권장드립니다 😊

2022-04-11 07:05 UTC, hoit1302 commented on 0405/1080.cpp
> +}
p3 
정말 사소한 변수 관련 코멘트인데요! 
보통 반복문은 i, j, k 순서로 시작되어서 짝지어지는 변수를 하나씩 더 써주신 것 같아요.
매개변수의 이름을 시작하는 행과 열을 표현해주는 이름으로 바꿔보는 건 어떨까요?
`ii` -> `row` 또는 `r` 로 표현하면 더 읽기 좋은 코드가 될 것 같습니다 🤗

2022-04-11 07:05 UTC, hoit1302 commented on 0405/11000.cpp
> +        ts.push_back(make_pair(t, s));
p3.
정말 사소하지만 `make_pair()` 함수를 사용하지 않고 `{}`으로 pair를 생성할 수 있습니다!
그래서 `ts.push_back({t, s});` 바로 이렇게 입력받으면 됩니다 ㅎㅎ

2022-04-11 07:05 UTC, hoit1302 commented on 0405/11000.cpp
> +}
p1.
pq에 들어있는 값은 모든 각 강의실의 **첫번째 강의**가 끝나는 시간이에요. 
어떤 강의실에는 강의가 3개가 배치될 수도 있는데, 2개의 강의를 진행한 후에도 해당 강의실에는 첫번째 강의가 끝난 시간만을 저장하고 있을 뿐, 정보를 갱신해주고 있지 않아요!!!

2022-04-11 07:05 UTC, hoit1302 commented on 0405/11000.cpp
> +}
그리고 사실 더 중요한 부분이 틀렸는데요,,! 
이 부분에 대해서 힌트를 드리자면 
이 문제는 튜터링에서 다뤘던 1931 회의실 배정과는 다른 문제에요. 
1931번은 **한 개의 회의실에 최대 몇 개의 회의가 가능할까?** 를 물어보고 있는데
11000번은 **모든 회의를 최소 몇 개의 회의실에 배정해야할까?** 입니다!
실시간으로 강의가 진행된다고 생각해봅시다!!!

2022-04-14 05:33 UTC, minkyung01 commented
말씀해주신 대로 1080번과 11000번 수정했습니다!
늦게 수정해서 죄송해요..ㅠㅠ

확인 한 번 부탁드립니다ㅎㅎ 
감사합니다!!

2022-04-14 10:25 UTC, hoit1302 approved these changes
그리디 과제 선택 3문제 제출 확인했습니다.
수고하셨습니다 !!!

2022-04-14 10:25 UTC, hoit1302 commented on 0405/1080.cpp
> +            }
이런 부분에서는 삼항 연산자를 써도 좋을 것 같아요!
```c++
mat_a[i][j] = (mat_a[i][j] - '0') ? '0' : '1';
```

2022-04-14 16:18 UTC, minkyung01 commented
말씀해주신 대로 수정했습니다!
호출 없이 머지하겠습니다 감사합니다ㅎㅎ

2022-04-14 16:19 UTC, merged