0325 과제 제출
Altu-Bitu-2/AltuBitu2_assignment pull request #7
Opened 2022-03-29 19:19 UTC by minkyung01

#### 내용 & 질문
> 2580번 예제에 대한 출력은 잘 나오는데 백준에서 틀렸다고 뜹니다...!
> 코드 점검 부탁드립니다ㅠㅠ

#### <기존 제출>
> 1205, 2580, 10971, 14888, 20055

#### <추가 제출>

2022-03-31 04:59 UTC, hoit1302 reviewed
구현 문제와 백트래킹 문제 모두 사실 난이도가 확실히 보통은 아니라고 생각했는데,,,
너무 잘 풀어주셨습니다 🥳
스도쿠 문제가 논리적 오류를 내포하고 있어서 p1으로 드렸습니다.
저도 찾는데 오래걸렸어요... 그래도 해결하고 나시면 너무 뿌듯하실겁니다 ❤
현재 필수 2문제, 선택 2문제 제출 확인했습니다.
오늘도 화이팅 하세요! 🥰

2022-03-31 04:59 UTC, hoit1302 commented on 0325/10971.cpp
> +    }
p3. 사소한 의견
종료 조건 전에 현재 cost 값이 최솟값보다 크거가 같을 경우에는 더 이상 깊게 탐색하지 않도록 코드를 추가해준다면 조금 더 가지치기를 할 수 있습니다 😊
```
if (cost >= minCost) {
    return;
}
```

2022-03-31 04:59 UTC, hoit1302 commented on 0325/10971.cpp
> +}
p3. 사소한 의견
`cnt` 변수는 `findRoute` 함수 내에서만 사용되는게 보이시죠?
`cnt` 변수는 `findRoute` 함수의 파라미터로 구현하는 것을 권장드립니다!
```
void findRoute(int cnt, int current, int cost) {
	...
	findRoute(cnt + 1, i, cost + travel[current][i]);
	...
```
이렇게 작성하면 함수 내에서 cnt 변수를 변경하고(32줄), 다시 회복(38줄)시키는 코드를 없앨 수 있기도 합니다.
보통 재귀의 깊이를 뜻하게 되는 파라미터가 첫번째 파라미터로 많이 쓰입니다!!!

2022-03-31 04:59 UTC, hoit1302 commented on 0325/1205.cpp
> +    }
p3. 사소한 의견
해당 로직을 함수로 작성하고 
`if ~ else` 대신 return -1; 과 같이 끊어주는 것을 권장드립니다! 
indent도 낮아지고, 가독성도 훨씬 좋습니다. 🤗

2022-03-31 04:59 UTC, hoit1302 commented on 0325/14888.cpp
> +    }
입력받을 때 불필요하게 변수 x와 y를 선언하고 사용하는 것이 혹시 불편하진 않으신가요?
벡터의 메모리를 할당한 뒤 index로 접근해 바로 입력받을 수 있습니다.
```c++
cin >> N; // N의 값을 입력받은 뒤
vector<int> numList(N, 0); // 원하는 사이즈만큼을 0으로 초기화해준 뒤
for (int i = 0; i < N; i++) {
    cin >> numList[i]; // 간편하게 입력받을 수 있습니다.
}
```

혹시 전역변수 선언을 해야한다면, 최대 사이즈만큼 생성해주시면 됩니다.
```c++
const int SIZE = 11;
vector<int> num(SIZE + 1);
```

2022-03-31 04:59 UTC, hoit1302 commented on 0325/2580.cpp
> +        //exit(0);
이 코드의 주석을 풀면 AC를 받을 수 있습니다.
반례입니다.
```
0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0
```
문제에서는 `스도쿠 판을 채우는 방법이 여럿인 경우는 그 중 하나만을 출력한다.` 라고 써져 있습니다.
그런데 현재 코드에서는 스도쿠를 채울 수 있는 모든 방법을 출력하고 있습니다!

2022-03-31 04:59 UTC, hoit1302 commented on 0325/2580.cpp
> +    }
p3 사소한 의견
이런 부분도 아래와 같이 끊어주시면 가독성이 높아집니다!
```c++
if (sudoku[r][c] != 0) {
    findAnswer(fill + 1);
    return;
}
for (int i = 0; i < 9; i++) {
```

2022-03-31 04:59 UTC, hoit1302 commented on 0325/2580.cpp
> +                Square[(r / 3) * 3 + (c / 3)][i + 1] = true;
한 줄로 작성할 수 있다는 사실을 알고 계신가요! 😊
편리합니다 ㅎㅎㅎ
```c++
Row[r][i + 1] = Col[c][i + 1] = Square[(r / 3) * 3 + (c / 3)][i + 1] = true;
```

2022-03-31 04:59 UTC, hoit1302 commented on 0325/2580.cpp
> +            if (Row[r][i + 1] == false && Col[c][i + 1] == false && Square[(r / 3) * 3 + (c / 3)][i + 1] == false) {
이 부분도 보통 아래와 같이 작성하는데, 혹시 바로 생각하기가 어렵다면 조금 더 천천히 시간을 가지고 적응해봅시다..!
```c++
if (!Row[r][i + 1] && !Col[c][i + 1] && !Square[(r / 3) * 3 + (c / 3)][i + 1]) {
```

2022-03-31 04:59 UTC, hoit1302 commented on 0325/2580.cpp
> +                Square[(i / 3) * 3 + (j / 3)][sudoku[i][j]] = true;
p1. 꼭 반영해주세요
아앗! 논리적 오류가 있어요ㅛ!!
sudoku[i][j] 입력값으로 9가 입력될 수 있는데
Row[9][9]로 선언해둬서 Row[0][9]는 접근이 불가능하지 않나요??
사이즈를 늘려야 할 것 같아요!

2022-03-31 04:59 UTC, hoit1302 commented on 0325/2580.cpp
> +        //exit(0);
하지만 코드를 강제종료한다는 것은 사실 바람직한 종료가 아니에요! 어떻게 해결할 수 있을까요?
재귀함수가 true/false를 리턴하도록 만들면 쉽게 구현할 수 있어요!
저는 [이 링크의 영상](https://youtu.be/6-NtLLVsYOE)에서 도움을 많이 받아서,, 첨부해드립니다 ㅎㅎ
코드를 구현은 해보셔서 아마 13분 30초 이후부터 보셔도 코드가 보일 것 같습니다.

2022-03-31 04:59 UTC, hoit1302 requested changes
p1 요청으로 수정

2022-04-06 05:59 UTC, minkyung01 commented
1205번, 10971번, 14888번 코멘트 주신 대로 수정했습니다!
그리고 2580번도 도움주신 대로 수정해서 백준에서 "맞았습니다" 떴습니다ㅠㅠ
코멘트 꼼꼼히 달아주시고 영상까지 첨부해주셔서 정말 감사드려요ㅎㅎㅎ!!!

매번 감사드립니다!!
마지막으로 코드 한 번씩만 확인 부탁드립니다ㅎㅎㅎ

2022-04-06 12:03 UTC, hoit1302 reviewed
수정까지 반영된 부분 모두 확인했습니다!
모두 너무 잘 수정해주셨습니다!!
스도쿠는 저도 처음 문제 풀 때 너어어무 어렵게 풀었던 기억이 있어서... 인상이 깊습니다... bool 리턴 관련까지 모두 이해하셨다면 백트래킹의 뼈대를 모두 이해하셨다고 봐도 될 것 같습니다 🥳
수고하셨습니다.

2022-04-06 14:33 UTC, merged